Sort Reject after RealImpl
ocaml-opam/opam-0install-solver pull request #33
Opened 2021-11-10 10:02 UTC by emillon

This improves error messages by displaying Rejects first.

2021-11-10 10:06 UTC, emillon commented
I have a few comments:
- I tried to add a test (first instantiating `Opam_0install.Model.Make(Opan_0install.Switch_context)`) but I'm not sure how to easily create values that will
  map to Reject and RealImpl.
- should the same fix be done in `lib-cudf`?
- after reading the code, it seems that the existing code is correct... `0install` displays the N maximum elements of the list, and polymorphic comparison should consider that `Reject` is greater than `RealImpl` since it is defined after. What am I missing?

2021-11-10 10:55 UTC, talex5 reviewed
Thanks!

> I tried to add a test (first instantiating `Opam_0install.Model.Make(Opan_0install.Switch_context)`) ...

Probably best to use `Dir_context` with some test-data checked into the repository. Otherwise, the test results might change as opam-repository is updated. If that seems like too much work, I'm happy to merge this without a test though.

> should the same fix be done in lib-cudf?

Yes, looks like it needs the same fix.

> after reading the code, it seems that the existing code is correct... 0install displays the N maximum elements of the list, and polymorphic comparison should consider that Reject is greater than RealImpl since it is defined after. What am I missing?

It does sort `Reject`s as greater, which is why they become the maximum elements and are shown. But we want to show the `RealImpl`s instead. i.e. we want to see versions that could have been chosen first, not versions that were immediately rejected at the start.

2021-11-10 10:56 UTC, talex5 commented
(rebasing onto `master` should fix the CI errors)

2021-11-10 11:06 UTC, kit-ty-kate requested changes
> should the same fix be done in `lib-cudf`?

Being explicit there as well wouldn’t hurt. However if this `compare_version` function is only used for diagnostics it should matter less given opam doesn’t use it at the moment (but it’s still good to fix anyway)

2021-11-10 11:06 UTC, kit-ty-kate commented on lib/model.ml
> +    | a, b -> compare b a
```suggestion
    | RealImpl a, Reject b -> OpamPackage.compare b a
    | Reject a, RealImpl b -> OpamPackage.compare a b
    | VirtualImpl _, _ -> 1
    | _, VirtualImpl _ -> -1
```
or something like that.
I think it would be safer to be explicit (especially with polymorphic compare) as the types can change without notice and break things very easily)

2021-11-10 13:45 UTC, emillon commented on lib/model.ml
> +    | a, b -> compare b a
I agree that we don't want to implicitly rely on the declaration order, this is why I wanted to add an explicit test. I think it's enough in that case.

2021-11-10 14:21 UTC, emillon commented
> Probably best to use `Dir_context` with some test-data checked into the repository.

I tried this but I'm stuck. I managed to create a context using `Dir_context.create` and instantiate `Solver` and `Model` modules compatible with it but I don't know how I can create values of type `impl` (one real and one fake) that I can compare.

2021-11-10 14:31 UTC, talex5 commented
I was imagining you'd put a few opam files in the test repository. e.g. `foo.1/opam`, `foo.2/opam` and `main.1/opam` (depends on `foo >= 2`). Then asking for a solution for `main` with user constraint `foo<2` should produce an error which lists foo.1 first because it meets the user's requirements, even though foo.2 is newer.

2021-11-16 10:58 UTC, emillon commented
I just tried that. I managed to get an error message but it only mentions
`foo.1`:

```
Can't find all required versions.
Selected: main.1
- foo -> (problem)
    User requested < 2
    main 1 requires >= 2
    Rejected candidates:
      foo.1: Incompatible with restriction: >= 2
```

Do you know what is going on?

2021-11-16 12:06 UTC, talex5 commented
That's expected; it thinks it's not worth listing versions that don't match the user's version constraint: https://github.com/0install/0install/blob/c3fea4a48e65fa15fdb834a0b4c2281128da886d/src/solver/diagnostics.ml#L144

If you change the constraint to reject all versions, then you will see it however.

You could try rejecting it for some other reason if you want to see it (e.g. incompatible arch).

2021-11-16 12:20 UTC, kit-ty-kate commented on lib/model.ml
> +    | a, b -> compare b a
I don’t think tests can accurately prevent bugs that can arise from user of polymorphic compare. Could my suggestion still be added?

2021-11-16 12:21 UTC, emillon commented
Thanks!
This is working now. I added a test and changing the comparison changes the
error message. I implemented that as a dune expect test (no extra dependencies)
but let me know if you prefer a different architecture.

2021-11-16 12:28 UTC, emillon commented
I added a commit to not rely on polymorphic comparison. I'm not convinced it improves the situation so I'll let @talex5 decide whether to keep it or not.

2021-11-16 13:22 UTC, talex5 approved these changes
That's great - thanks!

> I added a commit to not rely on polymorphic comparison. I'm not convinced it improves the situation so I'll let @talex5 decide whether to keep it or not

I don't have a strong opinion on this. It is a bit messy listing all the pair-wise combinations and having to check it's all correct, so I slightly prefer the polymorphic compare, but merging either version is fine with me.

2021-11-16 14:32 UTC, emillon commented
Let me suggest the following tradeoff: expand `_` into the full list of constructors. That way this ensures that this breaks when a constructor is added.

2021-11-16 16:05 UTC, kit-ty-kate approved these changes

2021-11-16 16:23 UTC, merged